* Gunnar notes
** Fiks impedans mismatch i intro mellom mitt og motivasjon
** Legg til et nivaa i figur fra MEA til reservoir kompatibelt sig
** Naturligvis fikse siste seksjon
   Tjaaaaaaaa
** Fikse siteringer (ta paa jobbmaskin)

** Fiks RC figur (feil tekst)
* Neste gang
** Bytte navn i figurer
** Exporte figurer
** Background fix-up
** Gå gjennom kap3 i lys av kap4
  
* Gunnar diskuser
** Om lineær vs ulineær
   Gunnar er enig i at reservoirer ikke nødvendigvis må ha en lineær output.
   Mitt eksempel er temporalitet, men f.eks mer effektivitet i trening på et problem, 
   eller i det hele tatt å løse oppgaven er jo ikke helt dumt.

** Strange attractor, complex eller chaotic?
   
* Abstract
* Intro
* Background
** Complexity
*** Få inn attractors
*** Få inn scale of observation
    
* Implement
** TODO beskrivelse av hva core RC computer faktisk er
* Experimental setup
  Endre figur til primary dataloop for a poengtere hva som er primary 
  dloop og hva som er core rc
* Conclusion & further work
  hehe
* Figurer
** DONE recreate Sipper fig
** OverView
   uhh, hva mente jeg her?
*** TODO Legg til stiplede 'boundaries'
*** TODO Kryssreferer med conceptual cyborg

* Figurer
** TODO Wolfram klasser

* Navnefiks
  Reservoir output -> res output preprocessor -> input layer
  output transform

* Thingken
  Kan vi gjøre et eksperiment for aa vise at reservoiret kan tilpasse
  seg til filteret?
  Hvis et reservoir har state som kan resettes, er det da mulig a vise
  at dersom vi ikke resetter sa konvergerer vi til et resultat raskere?
  
* Random
  Kan vi beskrive mulige stier gjennom et konfigurasjons-nett der 
  sykler blir oppdaget og stier som ikke oppfyller alle krav kan 
  oppdages?
  
  Worst case er det som å spørre om et system kommer til å stabilisere 
  seg uansett input (som å vise at en CA går til en quiescent state...)
