* Mastern

* Now
** TODO Forbedre Neuro computing background
* Later
** TODO Forbedre RC background
*** TODO Skaff figurer
*** TODO Skriv om lineær vs ulineær output classifiers

** TODO Lag TODOs for hovedinnhold
* Done
** DONE Skriv RC subchapter

   


* Funnies og quotes
** Matrix 
   Morpheus: What is real? How do you define 'real'? If you're talking about
   what you can feel, what you can smell, what you can taste and see, then
   'real' is simply electrical signals interpreted by your brain.

   
* Gunnar structure notes
** Intro
*** Goal
    Mer explicit på top down vs bottom up
    EIM ved mecobo
    
    kontrast mecobo analog-digital mot neuro-digital
*** "background"
    Få inn symbolsk logikk sammen med hw vekst
    
    På avalanches, få frem parallelitet og self organizing, men uten purpose dvs computation.
*** related work
*** method
    
** Background
*** Complex systems
    Ta CA ruten? Sipper -> Langton -> Adaptive systems??
    
    Flytte wolfram opp til general computation biten med turing machine etc.
    
    Finne cite på turing completeness for CA
    
*** EIM
    Med CA ↑ får vi criticality, vise til materie, særlig nascence som bruker samme tech (MEA)?
*** Neruo
    Skriv om mtp at nevro dyttes lenger bak
*** RC
    ???
*** Hybrid bio-digital
    
** Cyborg
*** Skikkelig beskrivelse
*** Implement

* Gunnar diskuser
** Om lineær vs ulineær
   Gunnar er enig i at reservoirer ikke nødvendigvis må ha en lineær output.
   Mitt eksempel er temporalitet, men f.eks mer effektivitet i trening på et problem, 
   eller i det hele tatt å løse oppgaven er jo ikke helt dumt.
